### ISSUE TITLE
[question] use case vs. firebase/flashlight

### ISSUE THREAD

**Issue by brandonmp** [deltaepsilon/firebase-search#1]
1. thanks for writing this & producing your youtube series. besides the company's own, I don't see a ton of coverage of firebase for advanced topics, so it's welcome.

2. can you help me understand how this library differs from https://github.com/firebase/flashlight ? besides algolia integration I mean. 

I'm new to elasticsearch, but not to firebase. thinking of adding elastic, so trying to understand diff't options.

thanks!

**Comment by deltaepsilon** [comment]
I've been missing out on my GitHub alerts :(

I'm sorry for missing this question!

You could definitely use Flashlight instead of firebase-search. I built it so that I could use either Elasticsearch or Algolia. Also, I just want a simpler API. firebase-search isn't much code. It's just an API interface layer to expose parts of the Elasticsearch and Algolia APIs, plus listeners for child_added, child_changed and child_removed.
